* FoxRemoteTests.prg - FoxRemote 1.0, the SQL it writes and what it does without a server.
*
* No database is needed: these tests build the library objects and look at what they generate
* (column types, CREATE TABLE, connection strings, :parameters, values) and at how they fail
* offline. The 0.x suite of this kind lives in legacy\FoxRemoteTests.prg.
*
* Run: foxproof run --prg tests\FoxRemoteTests.prg

DEFINE CLASS TestRemoteSql AS Custom

	PROCEDURE SetUp
		SET PROCEDURE TO "C:\Desarrollo\IrwinRodriguez.dev\FoxRemote\tests\TestSupport.prg" ADDITIVE
		IF !EMPTY(GETENV("FOXREMOTE_HOME"))
			SET PROCEDURE TO (ADDBS(GETENV("FOXREMOTE_HOME")) + "tests\TestSupport.prg") ADDITIVE
		ENDIF
		FrLoadLibrary()
		SET DECIMALS TO 2
	ENDPROC

	PROCEDURE TearDown
		SET DECIMALS TO 2
		CLOSE TABLES ALL
	ENDPROC

	* A test object of one engine, with protected members reachable through Call().
	FUNCTION Db(tcEngine)
		LOCAL loDb
		DO CASE
		CASE tcEngine == "sqlserver"
			loDb = CREATEOBJECT("XSqlServer")
		CASE tcEngine == "mysql"
			loDb = CREATEOBJECT("XMySql")
		CASE tcEngine == "mariadb"
			loDb = CREATEOBJECT("XMariaDb")
		CASE tcEngine == "postgresql"
			loDb = CREATEOBJECT("XPostgreSql")
		CASE tcEngine == "firebird"
			loDb = CREATEOBJECT("XFirebird")
		CASE tcEngine == "sqlite"
			loDb = CREATEOBJECT("XSqlite")
		ENDCASE
		RETURN loDb
	ENDFUNC

	* One call on a fresh object of one engine (nothing may be chained after a method in VFP).
	FUNCTION C(tcEngine, tcMethod, tv1, tv2, tv3, tv4)
		LOCAL loDb, lnN
		loDb = This.Db(tcEngine)
		lnN = PCOUNT()
		DO CASE
		CASE lnN = 2
			RETURN loDb.Call(tcMethod)
		CASE lnN = 3
			RETURN loDb.Call(tcMethod, tv1)
		CASE lnN = 4
			RETURN loDb.Call(tcMethod, tv1, tv2)
		CASE lnN = 5
			RETURN loDb.Call(tcMethod, tv1, tv2, tv3)
		ENDCASE
		RETURN loDb.Call(tcMethod, tv1, tv2, tv3, tv4)
	ENDFUNC

	FUNCTION P(tcEngine, tcProperty)
		LOCAL loDb
		loDb = This.Db(tcEngine)
		RETURN GETPEM(loDb, tcProperty)
	ENDFUNC

	* Asserts the SQL type of every VFP type for one engine.
	PROCEDURE CheckTypes(tcEngine, tcText, tcDouble, tcDateTime, tcBool, tcBlob, tcAutoKey)
		LOCAL loDb
		loDb = This.Db(tcEngine)
		__assert.Equal("VARCHAR(10)", loDb.Call("ColumnType", "C", 10, 0), tcEngine + " C(10)")
		__assert.Equal("VARCHAR(20)", loDb.Call("ColumnType", "V", 20, 0), tcEngine + " V(20)")
		__assert.Equal(tcText, loDb.Call("ColumnType", "M", 4, 0), tcEngine + " M")
		__assert.Equal("NUMERIC(10, 2)", loDb.Call("ColumnType", "N", 10, 2), tcEngine + " N(10,2)")
		__assert.Equal("INTEGER", loDb.Call("ColumnType", "I", 4, 0), tcEngine + " I")
		__assert.Equal(tcDouble, loDb.Call("ColumnType", "B", 8, 2), tcEngine + " B")
		__assert.Equal(tcDouble, loDb.Call("ColumnType", "F", 12, 3), tcEngine + " F")
		__assert.Equal("NUMERIC(19, 4)", loDb.Call("ColumnType", "Y", 8, 4), tcEngine + " Y")
		__assert.Equal("DATE", loDb.Call("ColumnType", "D", 8, 0), tcEngine + " D")
		__assert.Equal(tcDateTime, loDb.Call("ColumnType", "T", 8, 0), tcEngine + " T")
		__assert.Equal(tcBool, loDb.Call("ColumnType", "L", 1, 0), tcEngine + " L")
		__assert.Equal(tcBlob, loDb.Call("ColumnType", "G", 4, 0), tcEngine + " G")
		__assert.Equal(tcBlob, loDb.Call("ColumnType", "W", 4, 0), tcEngine + " W")
		__assert.Equal(tcAutoKey, loDb.Call("AutoKeyType"), tcEngine + " auto key")
	ENDPROC

	* ======================================================================== *
	* Column types
	* ======================================================================== *
	PROCEDURE TestTypesSqlServer() HELP [Fact, Trait("Category", "Types")]
		This.CheckTypes("sqlserver", "VARCHAR(MAX)", "FLOAT", "DATETIME2", "BIT", "VARBINARY(MAX)", "INT IDENTITY(1,1) PRIMARY KEY")
	ENDPROC

	PROCEDURE TestTypesMySql() HELP [Fact, Trait("Category", "Types")]
		This.CheckTypes("mysql", "LONGTEXT", "DOUBLE", "DATETIME", "TINYINT(1)", "LONGBLOB", "INT AUTO_INCREMENT PRIMARY KEY")
	ENDPROC

	PROCEDURE TestTypesMariaDb() HELP [Fact, Trait("Category", "Types")]
		This.CheckTypes("mariadb", "LONGTEXT", "DOUBLE", "DATETIME", "TINYINT(1)", "LONGBLOB", "INT AUTO_INCREMENT PRIMARY KEY")
	ENDPROC

	PROCEDURE TestTypesPostgreSql() HELP [Fact, Trait("Category", "Types")]
		This.CheckTypes("postgresql", "TEXT", "DOUBLE PRECISION", "TIMESTAMP", "BOOLEAN", "BYTEA", "SERIAL PRIMARY KEY")
	ENDPROC

	PROCEDURE TestTypesFirebird() HELP [Fact, Trait("Category", "Types")]
		This.CheckTypes("firebird", "BLOB SUB_TYPE TEXT", "DOUBLE PRECISION", "TIMESTAMP", "BOOLEAN", "BLOB", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	ENDPROC

	* SQLite: VARCHAR(n), not TEXT(n), which the driver hands to VFP as a memo (N3).
	PROCEDURE TestTypesSqlite() HELP [Fact, Trait("Category", "Types")]
		This.CheckTypes("sqlite", "TEXT", "REAL", "DATETIME", "INTEGER", "BLOB", "INTEGER PRIMARY KEY AUTOINCREMENT")
	ENDPROC

	PROCEDURE TestTypeOfAZeroWidthCharacterIsOne() HELP [Fact, Trait("Category", "Types")]
		__assert.Equal("VARCHAR(1)", This.C("postgresql", "ColumnType", "C", 0, 0))
	ENDPROC

	PROCEDURE TestNumericPrecisionIsCappedAt38() HELP [Fact, Trait("Category", "Types")]
		__assert.Equal("NUMERIC(38, 4)", This.C("sqlserver", "ColumnType", "N", 60, 4))
	ENDPROC

	* ======================================================================== *
	* Names (D11)
	* ======================================================================== *
	PROCEDURE TestNamesAreLowerCaseInPostgreSqlMySqlAndSqlite() HELP [Fact, Trait("Category", "Names")]
		__assert.Equal("customers", This.C("postgresql", "NaturalName", "Customers"))
		__assert.Equal("customers", This.C("mysql", "NaturalName", "CUSTOMERS"))
		__assert.Equal("customers", This.C("mariadb", "NaturalName", "Customers"))
		__assert.Equal("customers", This.C("sqlite", "NaturalName", " CUSTOMERS "))
	ENDPROC

	PROCEDURE TestNamesAreUpperCaseInFirebird() HELP [Fact, Trait("Category", "Names")]
		__assert.Equal("CUSTOMERS", This.C("firebird", "NaturalName", "customers"))
	ENDPROC

	PROCEDURE TestNamesAreKeptInSqlServer() HELP [Fact, Trait("Category", "Names")]
		__assert.Equal("Customers", This.C("sqlserver", "NaturalName", "Customers"))
	ENDPROC

	* Names from VFP (AFIELDS, .dbf files) come in capitals and carry no case: lower case in SQL Server.
	* The public methods are the ones README.md documents, and no more: a helper that is not part
	* of the API is PROTECTED (VfpName() was public in 1.0.0).
	PROCEDURE TestPublicMethodsAreTheDocumentedOnes() HELP [Fact, Trait("Category", "Surface")]
		LOCAL loDb, loBase, laM[1], laB[1], lnI, lcBase, lcActual, lcExpected
		loDb = CREATEOBJECT("RemoteSqlite")
		loBase = CREATEOBJECT("Custom")
		lcBase = ","
		FOR lnI = 1 TO AMEMBERS(laB, loBase, 1)
			lcBase = lcBase + UPPER(laB[lnI, 1]) + ","
		ENDFOR
		lcActual = ""
		FOR lnI = 1 TO AMEMBERS(laM, loDb, 1)
			IF laM[lnI, 2] == "Method" AND !(("," + UPPER(laM[lnI, 1]) + ",") $ lcBase)
				lcActual = lcActual + IIF(EMPTY(lcActual), "", ",") + UPPER(laM[lnI, 1])
			ENDIF
		ENDFOR
		lcExpected = "ATTACH,BEGINTRANSACTION,CLEARERRORS,CLOSE,CLOSEALL,CLOSEGROUP,COLUMNEXISTS,"
		lcExpected = lcExpected + "COMMIT,CONNECT,CREATEDATABASE,CREATETABLE,CREATETABLEFROMCURSOR,DATABASEEXISTS,"
		lcExpected = lcExpected + "DISCARD,DISCONNECT,EXECUTE,GENERATESCRIPT,GETCOLUMNS,GETPRIMARYKEY,GETTABLES,"
		lcExpected = lcExpected + "HASCHANGES,LASTID,MIGRATE,NATURALNAME,NEWGUID,NEWTABLEDEF,NEXTNUMBER,OPEN,PING,"
		lcExpected = lcExpected + "QUERY,REFRESH,ROLLBACK,SAVE,SAVEGROUP,SCALAR,SERVERDATE,SERVERVERSION,"
		lcExpected = lcExpected + "TABLEEXISTS,TABLESCRIPT,USEDATABASE"
		__assert.Equal(lcExpected, lcActual)
	ENDPROC

	PROCEDURE TestNamesFromVfpAreLowerCaseInSqlServer() HELP [Fact, Trait("Category", "Names")]
		__assert.Equal("customers", This.C("sqlserver", "VfpName", "CUSTOMERS"))
		__assert.Equal("CUSTOMERS", This.C("firebird", "VfpName", "customers"))
		__assert.Equal("customers", This.C("postgresql", "VfpName", "CUSTOMERS"))
	ENDPROC

	* N1: the catalog queries compare the plain name, never '"t"', '[t]' or '`t`'.
	PROCEDURE TestPrimaryKeyQueriesUseThePlainName() HELP [Fact, Trait("Category", "Names")]
		LOCAL laE[6], lnI, lcSql
		=ALINES(laE, "sqlserver,mysql,mariadb,postgresql,firebird,sqlite", 1, ",")
		FOR lnI = 1 TO ALEN(laE)
			lcSql = This.C(laE[lnI], "PrimaryKeySql", "customers")
			__assert.True("'customers'" $ lcSql, laE[lnI] + ": " + lcSql)
			__assert.False(['"customers"'] $ lcSql OR "[customers]" $ lcSql OR "`customers`" $ lcSql, laE[lnI] + " quotes the name: " + lcSql)
		ENDFOR
	ENDPROC

	PROCEDURE TestPrimaryKeyQueryEscapesQuotes() HELP [Fact, Trait("Category", "Names")]
		__assert.True("'o''hara'" $ This.C("postgresql", "PrimaryKeySql", "o'hara"))
	ENDPROC

	* ======================================================================== *
	* CREATE TABLE, indexes and foreign keys
	* ======================================================================== *
	PROCEDURE TestCreateTableColumnsAreNullableByDefault() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT
		loDb = This.Db("postgresql")
		loT = loDb.NewTableDef("Customers")
		loT.AddColumn("Name", "C", 40)
		__assert.Equal("CREATE TABLE customers (name VARCHAR(40));" + CHR(13) + CHR(10), loDb.TableScript(loT))
	ENDPROC

	PROCEDURE TestCreateTableNotNullAndDefault() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT, loC
		loDb = This.Db("sqlserver")
		loT = loDb.NewTableDef("stock")
		loC = loT.AddColumn("qty", "I")
		loC.lNullable = .F.
		loC.cDefault = "0"
		__assert.Equal("CREATE TABLE stock (qty INTEGER DEFAULT 0 NOT NULL)", loDb.Call("CreateTableSql", loT))
	ENDPROC

	PROCEDURE TestCreateTableCompositePrimaryKey() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT, loC
		loDb = This.Db("mariadb")
		loT = loDb.NewTableDef("lines")
		loC = loT.AddColumn("order_id", "I")
		loC.lPrimaryKey = .T.
		loC = loT.AddColumn("line_no", "I")
		loC.lPrimaryKey = .T.
		__assert.Equal("CREATE TABLE lines (order_id INTEGER, line_no INTEGER, PRIMARY KEY (order_id, line_no))", loDb.Call("CreateTableSql", loT))
	ENDPROC

	PROCEDURE TestCreateTableAutoIncrementColumn() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT, loC
		loDb = This.Db("sqlserver")
		loT = loDb.NewTableDef("orders")
		loC = loT.AddColumn("id", "I")
		loC.lAutoIncrement = .T.
		loT.AddColumn("total", "Y")
		__assert.Equal("CREATE TABLE orders (id INT IDENTITY(1,1) PRIMARY KEY, total NUMERIC(19, 4))", loDb.Call("CreateTableSql", loT))
	ENDPROC

	* D8: no automatic key column unless cAutoKeyName says so.
	PROCEDURE TestCreateTableHasNoAutomaticKeyByDefault() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT
		loDb = This.Db("postgresql")
		loT = loDb.NewTableDef("t")
		loT.AddColumn("name", "C", 10)
		__assert.Equal("CREATE TABLE t (name VARCHAR(10))", loDb.Call("CreateTableSql", loT))
	ENDPROC

	PROCEDURE TestCreateTableWithAutoKeyName() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT
		loDb = This.Db("postgresql")
		loDb.cAutoKeyName = "ID"
		loT = loDb.NewTableDef("t")
		loT.AddColumn("name", "C", 10)
		__assert.Equal("CREATE TABLE t (id SERIAL PRIMARY KEY, name VARCHAR(10))", loDb.Call("CreateTableSql", loT))
	ENDPROC

	PROCEDURE TestCreateTableNamesAreUpperCaseInFirebird() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT
		loDb = This.Db("firebird")
		loT = loDb.NewTableDef("customers")
		loT.AddColumn("name", "C", 40)
		__assert.Equal("CREATE TABLE CUSTOMERS (NAME VARCHAR(40))", loDb.Call("CreateTableSql", loT))
	ENDPROC

	PROCEDURE TestCreateTableNeverQuotesNames() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL laE[6], lnI, loDb, loT, lcSql
		=ALINES(laE, "sqlserver,mysql,mariadb,postgresql,firebird,sqlite", 1, ",")
		FOR lnI = 1 TO ALEN(laE)
			loDb = This.Db(laE[lnI])
			loT = loDb.NewTableDef("customers")
			loT.AddColumn("name", "C", 40)
			loT.AddIndex("ix_name", "name")
			loT.AddForeignKey("name", "people", "name")
			lcSql = loDb.TableScript(loT)
			__assert.False('"' $ lcSql OR "[" $ lcSql OR "`" $ lcSql, laE[lnI] + ": " + lcSql)
		ENDFOR
	ENDPROC

	PROCEDURE TestForeignKeyWithActions() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT, lcSql
		loDb = This.Db("postgresql")
		loT = loDb.NewTableDef("orders")
		loT.AddColumn("customer_id", "I")
		loT.AddForeignKey("customer_id", "customers", "id", "CASCADE", "NO ACTION")
		lcSql = loDb.Call("CreateTableSql", loT)
		__assert.True("FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE ON UPDATE NO ACTION" $ lcSql, lcSql)
	ENDPROC

	PROCEDURE TestForeignKeyActionShortcuts() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb
		loDb = This.Db("mysql")
		__assert.Equal("SET NULL", loDb.Call("ForeignKeyAction", "NULL"))
		__assert.Equal("SET NULL", loDb.Call("ForeignKeyAction", "null"))
		__assert.Equal("SET DEFAULT", loDb.Call("ForeignKeyAction", "Default"))
		__assert.Equal("CASCADE", loDb.Call("ForeignKeyAction", "cascade"))
		__assert.Equal("RESTRICT", loDb.Call("ForeignKeyAction", "RESTRICT"))
	ENDPROC

	PROCEDURE TestForeignKeyRestrictIsNoActionInSqlServer() HELP [Fact, Trait("Category", "CreateTable")]
		__assert.Equal("NO ACTION", This.C("sqlserver", "ForeignKeyAction", "RESTRICT"))
		__assert.Equal("SET NULL", This.C("sqlserver", "ForeignKeyAction", "null"))
	ENDPROC

	PROCEDURE TestForeignKeyWithoutActions() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT, lcSql
		loDb = This.Db("sqlite")
		loT = loDb.NewTableDef("orders")
		loT.AddColumn("customer_id", "I")
		loT.AddForeignKey("customer_id", "customers", "id")
		lcSql = loDb.Call("CreateTableSql", loT)
		__assert.True("FOREIGN KEY (customer_id) REFERENCES customers (id))" $ lcSql AND !("ON DELETE" $ lcSql) AND !("ON UPDATE" $ lcSql), lcSql)
	ENDPROC

	PROCEDURE TestCompositeForeignKey() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT, lcSql
		loDb = This.Db("firebird")
		loT = loDb.NewTableDef("notes")
		loT.AddColumn("order_id", "I")
		loT.AddColumn("line_no", "I")
		loT.AddForeignKey("order_id, line_no", "lines", "order_id,line_no")
		lcSql = loDb.Call("CreateTableSql", loT)
		__assert.True("FOREIGN KEY (ORDER_ID, LINE_NO) REFERENCES LINES (ORDER_ID, LINE_NO)" $ lcSql, lcSql)
	ENDPROC

	PROCEDURE TestIndexesFollowTheTable() HELP [Fact, Trait("Category", "CreateTable")]
		LOCAL loDb, loT, laL[1], lnN
		loDb = This.Db("sqlserver")
		loT = loDb.NewTableDef("customers")
		loT.AddColumn("name", "C", 40)
		loT.AddColumn("city", "C", 40)
		loT.AddIndex("ix_name", "name", .T.)
		loT.AddIndex("ix_city_name", "city, name")
		lnN = ALINES(laL, loDb.TableScript(loT), 1)
		__assert.Equal(3, lnN)
		__assert.Equal("CREATE TABLE customers (name VARCHAR(40), city VARCHAR(40));", laL[1])
		__assert.Equal("CREATE UNIQUE INDEX ix_name ON customers (name);", laL[2])
		__assert.Equal("CREATE INDEX ix_city_name ON customers (city, name);", laL[3])
	ENDPROC

	* ======================================================================== *
	* Connection strings
	* ======================================================================== *
	PROCEDURE TestConnectionStringSqlServer() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb
		loDb = This.Db("sqlserver")
		loDb.cDriver = "ODBC Driver 17 for SQL Server"
		loDb.cServer = "localhost\SQLEXPRESS"
		loDb.cUser = "app"
		loDb.cPassword = "secret"
		__assert.Equal("DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost\SQLEXPRESS;DATABASE=erp;UID=app;PWD=secret;APP=FoxRemote;", ;
			loDb.Call("BuildConnectionString", "erp"))
	ENDPROC

	PROCEDURE TestConnectionStringSqlServerPortGoesAfterAComma() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb
		loDb = This.Db("sqlserver")
		loDb.cServer = "db.example.com"
		loDb.nPort = 1433
		__assert.True("SERVER=db.example.com,1433;" $ loDb.Call("BuildConnectionString", "erp"))
	ENDPROC

	PROCEDURE TestConnectionStringSqlServerWindowsAuthentication() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb, lcConn
		loDb = This.Db("sqlserver")
		loDb.cUser = "ignored"
		loDb.lTrustedConnection = .T.
		lcConn = loDb.Call("BuildConnectionString", "erp")
		__assert.True("Trusted_Connection=yes;" $ lcConn, lcConn)
		__assert.False("UID=" $ lcConn OR "PWD=" $ lcConn, lcConn)
	ENDPROC

	* F10: a value with ';' goes inside {} (measured: so it gets through to SQL Server, MariaDB, PostgreSQL, Firebird).
	PROCEDURE TestConnectionValueWithASemicolonIsBraced() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb
		loDb = This.Db("mariadb")
		loDb.cUser = "app"
		loDb.cPassword = "ab;cd"
		__assert.True("PWD={ab;cd};" $ loDb.Call("BuildConnectionString", "shop"))
	ENDPROC

	PROCEDURE TestConnectionValueWithABraceIsDoubled() HELP [Fact, Trait("Category", "Connection")]
		__assert.Equal("{a}}b}", This.C("postgresql", "Value", "a}b"))
		__assert.Equal("{a{b}", This.C("postgresql", "Value", "a{b"))
	ENDPROC

	PROCEDURE TestConnectionValueWithEqualsOrBlanksIsBraced() HELP [Fact, Trait("Category", "Connection")]
		__assert.Equal("{a=b}", This.C("firebird", "Value", "a=b"))
		__assert.Equal("{ pass}", This.C("firebird", "Value", " pass"))
		__assert.Equal("plain", This.C("firebird", "Value", "plain"))
	ENDPROC

	* N10: 0.x wrote PORT=5432.00 (SET DECIMALS) and PostgreSQL refused every connection.
	PROCEDURE TestConnectionStringPortHasNoDecimals() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb
		SET DECIMALS TO 4
		loDb = This.Db("postgresql")
		loDb.nPort = 5432
		__assert.True("PORT=5432;" $ loDb.Call("BuildConnectionString", "shop"))
		loDb = This.Db("mysql")
		loDb.nPort = 3306
		__assert.True("PORT=3306;" $ loDb.Call("BuildConnectionString", "shop"))
	ENDPROC

	PROCEDURE TestConnectionStringPostgreSqlDefaults() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb, lcConn
		loDb = This.Db("postgresql")
		loDb.cDriver = "PostgreSQL ANSI"
		loDb.cServer = "127.0.0.1"
		lcConn = loDb.Call("BuildConnectionString", "")
		__assert.True("PORT=5432;" $ lcConn AND "DATABASE=postgres;" $ lcConn, lcConn)
	ENDPROC

	PROCEDURE TestConnectionStringMySqlWithoutPort() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb, lcConn
		loDb = This.Db("mysql")
		loDb.cServer = "127.0.0.1"
		lcConn = loDb.Call("BuildConnectionString", "shop")
		__assert.False("PORT=" $ lcConn, lcConn)
		__assert.True("DATABASE=shop;" $ lcConn, lcConn)
	ENDPROC

	PROCEDURE TestConnectionStringFirebird() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb
		loDb = This.Db("firebird")
		loDb.cDriver = "Firebird ODBC Driver"
		loDb.cUser = "SYSDBA"
		loDb.cPassword = "pw"
		__assert.Equal("DRIVER={Firebird ODBC Driver};DBNAME=127.0.0.1/3050:C:\data\shop.fdb;UID=SYSDBA;PWD=pw;CHARSET=WIN1252;", ;
			loDb.Call("BuildConnectionString", "127.0.0.1/3050:C:\data\shop.fdb"))
	ENDPROC

	PROCEDURE TestConnectionStringSqlite() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb
		loDb = This.Db("sqlite")
		loDb.cDriver = "SQLite3 ODBC Driver"
		__assert.Equal("DRIVER={SQLite3 ODBC Driver};DATABASE=C:\data\shop.db;NoWCHAR=1;FKSupport=1;", loDb.Call("BuildConnectionString", "C:\data\shop.db"))
	ENDPROC

	* The SQLite driver does not read DATABASE={...}: a ';' in the path goes as a file: URI (measured).
	PROCEDURE TestConnectionStringSqlitePathWithASemicolonIsAnUri() HELP [Fact, Trait("Category", "Connection")]
		__assert.Equal("file:C:/my%20data/a%3Bb/shop.db", This.C("sqlite", "FileName", "C:\my data\a;b\shop.db"))
		__assert.Equal("C:\my data\shop.db", This.C("sqlite", "FileName", "C:\my data\shop.db"))
	ENDPROC

	PROCEDURE TestConnectionOptionsAreAppended() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb
		loDb = This.Db("sqlserver")
		loDb.cConnectionOptions = "Encrypt=no"
		__assert.True(RIGHT(loDb.Call("BuildConnectionString", "erp"), 11) == "Encrypt=no;")
	ENDPROC

	PROCEDURE TestFirebirdLocalPathForTheExistenceCheck() HELP [Fact, Trait("Category", "Connection")]
		LOCAL loDb
		loDb = This.Db("firebird")
		__assert.Equal("C:\data\shop.fdb", loDb.Call("LocalPath", "127.0.0.1/3050:C:\data\shop.fdb"))
		__assert.Equal("C:\data\shop.fdb", loDb.Call("LocalPath", "localhost:C:\data\shop.fdb"))
		__assert.Equal("C:\data\shop.fdb", loDb.Call("LocalPath", "C:\data\shop.fdb"))
		__assert.Equal("", loDb.Call("LocalPath", "dbserver/3050:/srv/shop.fdb"))
		__assert.Equal("", loDb.Call("LocalPath", "employee"))
	ENDPROC

	* ======================================================================== *
	* :parameters
	* ======================================================================== *
	PROCEDURE TestParameterIsTranslated() HELP [Fact, Trait("Category", "Parameters")]
		__assert.Equal("SELECT * FROM t WHERE city = ?loP.city", This.C("sqlserver", "TranslateParams", "SELECT * FROM t WHERE city = :city", "loP"))
	ENDPROC

	PROCEDURE TestSeveralParameters() HELP [Fact, Trait("Category", "Parameters")]
		__assert.Equal("INSERT INTO t (a, b) VALUES (?loP.p_1, ?loP.p2)", This.C("sqlite", "TranslateParams", "INSERT INTO t (a, b) VALUES (:p_1, :p2)", "loP"))
	ENDPROC

	PROCEDURE TestParameterInsideQuotesIsLeftAlone() HELP [Fact, Trait("Category", "Parameters")]
		__assert.Equal("SELECT ':x', " + '":y"' + " FROM t WHERE a = ?loP.a", This.C("mysql", "TranslateParams", "SELECT ':x', " + '":y"' + " FROM t WHERE a = :a", "loP"))
	ENDPROC

	PROCEDURE TestPostgreSqlCastIsLeftAlone() HELP [Fact, Trait("Category", "Parameters")]
		__assert.Equal("SELECT ?loP.v::int", This.C("postgresql", "TranslateParams", "SELECT :v::int", "loP"))
		__assert.Equal("SELECT x::text FROM t", This.C("postgresql", "TranslateParams", "SELECT x::text FROM t", "loP"))
	ENDPROC

	PROCEDURE TestColonBeforeADigitIsNotAParameter() HELP [Fact, Trait("Category", "Parameters")]
		__assert.Equal("SELECT 1 FROM t WHERE h > 10:30", This.C("firebird", "TranslateParams", "SELECT 1 FROM t WHERE h > 10:30", "loP"))
	ENDPROC

	PROCEDURE TestSqlWithoutParametersIsUnchanged() HELP [Fact, Trait("Category", "Parameters")]
		__assert.Equal("SELECT 1", This.C("sqlite", "TranslateParams", "SELECT 1", "loP"))
	ENDPROC

	* N9: SQLite stores UTF-8 and its driver does not convert: the parameters go converted.
	PROCEDURE TestSqliteParametersGoAsUtf8() HELP [Fact, Trait("Category", "Parameters")]
		LOCAL loP, loOut
		loP = CREATEOBJECT("Empty")
		ADDPROPERTY(loP, "name", "Pe" + CHR(241) + "a")
		ADDPROPERTY(loP, "qty", 3)
		loOut = This.C("sqlite", "PrepareParams", loP)
		__assert.Equal(STRCONV("Pe" + CHR(241) + "a", 9), loOut.name)
		__assert.Equal(3, loOut.qty)
		__assert.Equal("Pe" + CHR(241) + "a", loP.name, "the caller's object must not change")
	ENDPROC

	PROCEDURE TestOtherEnginesParametersAreNotConverted() HELP [Fact, Trait("Category", "Parameters")]
		LOCAL loP, loOut
		loP = CREATEOBJECT("Empty")
		ADDPROPERTY(loP, "name", "Pe" + CHR(241) + "a")
		loOut = This.C("sqlserver", "PrepareParams", loP)
		__assert.Equal("Pe" + CHR(241) + "a", loOut.name)
	ENDPROC

	* ======================================================================== *
	* INSERT and the new id in the same round trip
	* ======================================================================== *
	PROCEDURE TestInsertSqlServerReadsScopeIdentity() HELP [Fact, Trait("Category", "Insert")]
		__assert.Equal("SET NOCOUNT ON; INSERT INTO t (name) VALUES (:p1); SET NOCOUNT OFF; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS id", This.C("sqlserver", "InsertSql", "t", "name", ":p1", "id"))
	ENDPROC

	PROCEDURE TestInsertReturningEngines() HELP [Fact, Trait("Category", "Insert")]
		__assert.Equal("INSERT INTO t (name) VALUES (:p1) RETURNING id", This.C("postgresql", "InsertSql", "t", "name", ":p1", "id"))
		__assert.Equal("INSERT INTO t (name) VALUES (:p1) RETURNING id", This.C("mariadb", "InsertSql", "t", "name", ":p1", "id"))
		__assert.Equal("INSERT INTO t (name) VALUES (:p1) RETURNING id", This.C("sqlite", "InsertSql", "t", "name", ":p1", "id"))
		__assert.Equal("INSERT INTO t (name) VALUES (:p1) RETURNING ID", This.C("firebird", "InsertSql", "t", "name", ":p1", "id"))
	ENDPROC

	PROCEDURE TestMySqlDoesNotReturn() HELP [Fact, Trait("Category", "Insert")]
		__assert.False(This.P("mysql", "lReturning"))
		__assert.True(This.P("mariadb", "lReturning"))
	ENDPROC

	PROCEDURE TestInsertWithoutColumnsUsesDefaultValues() HELP [Fact, Trait("Category", "Insert")]
		__assert.Equal("INSERT INTO t DEFAULT VALUES RETURNING id", This.C("postgresql", "InsertSql", "t", "", "", "id"))
		__assert.Equal("SET NOCOUNT ON; INSERT INTO t DEFAULT VALUES; SET NOCOUNT OFF; SELECT CAST(SCOPE_IDENTITY() AS bigint) AS id", This.C("sqlserver", "InsertSql", "t", "", "", "id"))
	ENDPROC

	* ======================================================================== *
	* Values as they travel
	* ======================================================================== *
	PROCEDURE TestTextIsTrimmedOnSave() HELP [Fact, Trait("Category", "Values")]
		LOCAL loDb
		loDb = This.Db("sqlserver")
		__assert.Equal("short", loDb.Call("ToServerValue", "short     ", "C", .T.))
		loDb.lTrimOnSave = .F.
		__assert.Equal("short     ", loDb.Call("ToServerValue", "short     ", "C", .T.))
	ENDPROC

	* D5: an empty date is NULL when the column admits it.
	PROCEDURE TestEmptyDateIsNullWhenNullable() HELP [Fact, Trait("Category", "Values")]
		__assert.True(ISNULL(This.C("mariadb", "ToServerValue", {}, "D", .T.)))
		__assert.True(ISNULL(This.C("postgresql", "ToServerValue", {/:}, "T", .T.)))
	ENDPROC

	PROCEDURE TestEmptyDateIsTheMinimumWhenNotNullable() HELP [Fact, Trait("Category", "Values")]
		__assert.Equal(DATE(1753, 1, 1), This.C("sqlserver", "ToServerValue", {}, "D", .F.))
		__assert.Equal(DATE(1000, 1, 1), This.C("mysql", "ToServerValue", {}, "D", .F.))
		__assert.Equal(DTOT(DATE(1753, 1, 1)), This.C("firebird", "ToServerValue", {/:}, "T", .F.))
	ENDPROC

	PROCEDURE TestEmptyDateModeMin() HELP [Fact, Trait("Category", "Values")]
		LOCAL loDb
		loDb = This.Db("mariadb")
		loDb.cEmptyDateMode = "min"
		__assert.Equal(DATE(1000, 1, 1), loDb.Call("ToServerValue", {}, "D", .T.))
	ENDPROC

	PROCEDURE TestValuesThatTravelAsTheyAre() HELP [Fact, Trait("Category", "Values")]
		LOCAL loDb
		loDb = This.Db("postgresql")
		__assert.Equal(DATE(2026, 10, 4), loDb.Call("ToServerValue", DATE(2026, 10, 4), "D", .T.))
		__assert.Equal(12.5, loDb.Call("ToServerValue", 12.5, "N", .T.))
		__assert.True(ISNULL(loDb.Call("ToServerValue", .NULL., "C", .T.)))
		__assert.Equal("memo  ", loDb.Call("ToServerValue", "memo  ", "M", .T.), "a memo keeps its blanks")
	ENDPROC

	* VFP receives BIGINT (COUNT(*), LAST_INSERT_ID()) as C(20).
	PROCEDURE TestBigIntTextBecomesANumber() HELP [Fact, Trait("Category", "Values")]
		LOCAL loDb
		loDb = This.Db("mariadb")
		__assert.Equal(123, loDb.Call("BigIntValue", "123                 ", "C", 20))
		__assert.Equal(-7, loDb.Call("BigIntValue", "-7", "C", 19))
	ENDPROC

	PROCEDURE TestOtherTextStaysText() HELP [Fact, Trait("Category", "Values")]
		LOCAL loDb
		loDb = This.Db("mariadb")
		__assert.Equal("00123", loDb.Call("BigIntValue", "00123", "C", 10))
		__assert.Equal("12a", loDb.Call("BigIntValue", "12a", "C", 20))
	ENDPROC

	PROCEDURE TestMinimumDates() HELP [Fact, Trait("Category", "Values")]
		__assert.Equal(DATE(1753, 1, 1), This.C("sqlserver", "MinDate"))
		__assert.Equal(DATE(1000, 1, 1), This.C("mariadb", "MinDate"))
		* SQLite keeps dates as text: the base minimum (DATE(1, 1, 1) is not a valid VFP date).
		__assert.Equal(DATE(1753, 1, 1), This.C("sqlite", "MinDate"))
	ENDPROC

	* ======================================================================== *
	* Without a server
	* ======================================================================== *
	PROCEDURE TestDefaults() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb
		loDb = CREATEOBJECT("RemotePostgreSql")
		__assert.Equal("1.0.1", loDb.cVersion)
		__assert.Equal(0, loDb.nErrors)
		__assert.False(loDb.lStrict)
		__assert.Equal("null", loDb.cEmptyDateMode)
		__assert.True(loDb.lTrimOnSave)
		__assert.Equal("", loDb.cAutoKeyName)
		__assert.Equal(15, loDb.nConnectTimeout)
		__assert.Equal(0, loDb.nHandle)
	ENDPROC

	PROCEDURE TestExecuteWithoutAConnection() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb
		loDb = CREATEOBJECT("RemoteSqlServer")
		__assert.Equal(-1, loDb.Execute("DELETE FROM t"))
		__assert.Equal("not_connected", loDb.cLastErrorCode)
		__assert.Equal(1, loDb.nErrors)
		__assert.Equal("DELETE FROM t", loDb.cLastSql)
	ENDPROC

	PROCEDURE TestStrictRaisesWithoutAConnection() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb, llThrown
		loDb = CREATEOBJECT("RemoteMariaDb")
		loDb.lStrict = .T.
		llThrown = .F.
		TRY
			loDb.Query("SELECT 1", "c_x")
		CATCH
			llThrown = .T.
		ENDTRY
		__assert.True(llThrown)
		__assert.Equal("not_connected", loDb.cLastErrorCode)
	ENDPROC

	PROCEDURE TestClearErrors() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb
		loDb = CREATEOBJECT("RemoteSqlite")
		loDb.Execute("SELECT 1")
		loDb.ClearErrors()
		__assert.Equal(0, loDb.nErrors)
		__assert.Equal("", loDb.cLastErrorCode)
		__assert.Equal("", loDb.cLastError)
	ENDPROC

	PROCEDURE TestSaveOfAnAliasNotOpenedByFoxRemote() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb
		CREATE CURSOR c_mine (x I)
		loDb = CREATEOBJECT("RemotePostgreSql")
		__assert.False(loDb.Save("c_mine"))
		__assert.Equal("not_open", loDb.cLastErrorCode)
		USE IN c_mine
	ENDPROC

	PROCEDURE TestTransactionsNeedAConnection() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb
		loDb = CREATEOBJECT("RemoteFirebird")
		__assert.False(loDb.BeginTransaction())
		__assert.Equal("not_connected", loDb.cLastErrorCode)
		__assert.False(loDb.Commit())
		__assert.Equal("no_transaction", loDb.cLastErrorCode)
		__assert.False(loDb.Rollback())
		__assert.Equal("no_transaction", loDb.cLastErrorCode)
	ENDPROC

	* F3: a SQLite file that does not exist is not created by Connect().
	PROCEDURE TestSqliteConnectToAMissingFile() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb, lcFile
		lcFile = ADDBS(SYS(2023)) + "fr_missing_" + SYS(2015) + ".db"
		loDb = CREATEOBJECT("RemoteSqlite")
		loDb.cDriver = "SQLite3 ODBC Driver"
		loDb.cDatabase = lcFile
		__assert.False(loDb.Connect())
		__assert.Equal("database_not_found", loDb.cLastErrorCode)
		__assert.False(FILE(lcFile))
	ENDPROC

	PROCEDURE TestAttachNeedsAHandle() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb
		loDb = CREATEOBJECT("RemoteMySql")
		__assert.False(loDb.Attach(0))
		__assert.Equal("connection_failed", loDb.cLastErrorCode)
	ENDPROC

	PROCEDURE TestMigrateOfNothing() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb, loR
		loDb = CREATEOBJECT("RemotePostgreSql")
		loR = loDb.Migrate(ADDBS(SYS(2023)) + "no_such_" + SYS(2015) + ".dbf")
		__assert.Equal(1, loR.nErrors)
		__assert.Equal(0, loR.nTables)
		__assert.Equal("bad_argument", loDb.cLastErrorCode)
	ENDPROC

	PROCEDURE TestOpenNeedsATable() HELP [Fact, Trait("Category", "Offline")]
		LOCAL loDb
		loDb = CREATEOBJECT("RemoteSqlServer")
		__assert.False(loDb.Open(""))
		__assert.Equal("bad_argument", loDb.cLastErrorCode)
	ENDPROC

	* ======================================================================== *
	* GenerateScript: the SQL of a .dbf, without a server
	* ======================================================================== *
	PROCEDURE TestGenerateScriptOfADbf() HELP [Fact, Trait("Category", "Migration")]
		LOCAL loDb, lcDbf, lcScript, lcStem
		lcStem = "Fr_Gen" + SUBSTR(SYS(2015), 2)
		lcDbf = ADDBS(SYS(2023)) + lcStem + ".dbf"
		CREATE TABLE (lcDbf) FREE (NAME C(20), BORN D NULL, AMOUNT N(10, 2), NOTES M)
		USE IN (lcStem)
		loDb = CREATEOBJECT("RemotePostgreSql")
		lcScript = loDb.GenerateScript(lcDbf)
		__assert.Equal("CREATE TABLE " + LOWER(lcStem) + " (name VARCHAR(20), born DATE, amount NUMERIC(10, 2), notes TEXT);" + CHR(13) + CHR(10), lcScript)
		loDb = CREATEOBJECT("RemoteFirebird")
		lcScript = loDb.GenerateScript(lcDbf)
		__assert.Equal("CREATE TABLE " + UPPER(lcStem) + " (NAME VARCHAR(20), BORN DATE, AMOUNT NUMERIC(10, 2), NOTES BLOB SUB_TYPE TEXT);" + CHR(13) + CHR(10), lcScript)
		ERASE (lcDbf)
		ERASE (FORCEEXT(lcDbf, "fpt"))
	ENDPROC

	* (Never a..j as a table name in a test: USE IN b closes work area 2, not the table b.)
	PROCEDURE TestGenerateScriptOfAFolder() HELP [Fact, Trait("Category", "Migration")]
		LOCAL loDb, lcDir, lcScript, laL[1]
		lcDir = ADDBS(SYS(2023)) + "fr_gen_dir" + SUBSTR(SYS(2015), 2)
		MKDIR (lcDir)
		CREATE TABLE (ADDBS(lcDir) + "t1") FREE (x I)
		USE IN t1
		CREATE TABLE (ADDBS(lcDir) + "t2") FREE (y C(5))
		USE IN t2
		loDb = CREATEOBJECT("RemoteSqlServer")
		lcScript = loDb.GenerateScript(lcDir)
		__assert.Equal(2, ALINES(laL, lcScript, 1))
		__assert.True("CREATE TABLE t1 (x INTEGER);" $ lcScript, lcScript)
		__assert.True("CREATE TABLE t2 (y VARCHAR(5));" $ lcScript, lcScript)
		ERASE (ADDBS(lcDir) + "t1.dbf")
		ERASE (ADDBS(lcDir) + "t2.dbf")
		RMDIR (lcDir)
	ENDPROC

	PROCEDURE TestGenerateScriptLeavesTheDefaultFolder() HELP [Fact, Trait("Category", "Migration")]
		LOCAL loDb, lcDir, lcBefore
		lcDir = ADDBS(SYS(2023)) + "fr_gen_cd" + SUBSTR(SYS(2015), 2)
		MKDIR (lcDir)
		CREATE TABLE (ADDBS(lcDir) + "t3") FREE (x I)
		USE IN t3
		lcBefore = SYS(5) + SYS(2003)
		loDb = CREATEOBJECT("RemoteMySql")
		loDb.GenerateScript(lcDir)
		__assert.Equal(lcBefore, SYS(5) + SYS(2003))
		__assert.False(USED("c_fr_src_t3"), "the source table was left open")
		ERASE (ADDBS(lcDir) + "t3.dbf")
		RMDIR (lcDir)
	ENDPROC
ENDDEFINE

* ======================================================================== *
* Test subclasses: Call() reaches the protected members from inside the class.
* ======================================================================== *

DEFINE CLASS XSqlServer AS RemoteSqlServer
	FUNCTION Call(tcMethod, tv1, tv2, tv3, tv4)
		LOCAL lnN
		lnN = PCOUNT()
		DO CASE
		CASE lnN = 1
			RETURN EVALUATE("This." + tcMethod + "()")
		CASE lnN = 2
			RETURN EVALUATE("This." + tcMethod + "(tv1)")
		CASE lnN = 3
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2)")
		CASE lnN = 4
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3)")
		ENDCASE
		RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3, tv4)")
	ENDFUNC
ENDDEFINE

DEFINE CLASS XMySql AS RemoteMySql
	FUNCTION Call(tcMethod, tv1, tv2, tv3, tv4)
		LOCAL lnN
		lnN = PCOUNT()
		DO CASE
		CASE lnN = 1
			RETURN EVALUATE("This." + tcMethod + "()")
		CASE lnN = 2
			RETURN EVALUATE("This." + tcMethod + "(tv1)")
		CASE lnN = 3
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2)")
		CASE lnN = 4
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3)")
		ENDCASE
		RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3, tv4)")
	ENDFUNC
ENDDEFINE

DEFINE CLASS XMariaDb AS RemoteMariaDb
	FUNCTION Call(tcMethod, tv1, tv2, tv3, tv4)
		LOCAL lnN
		lnN = PCOUNT()
		DO CASE
		CASE lnN = 1
			RETURN EVALUATE("This." + tcMethod + "()")
		CASE lnN = 2
			RETURN EVALUATE("This." + tcMethod + "(tv1)")
		CASE lnN = 3
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2)")
		CASE lnN = 4
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3)")
		ENDCASE
		RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3, tv4)")
	ENDFUNC
ENDDEFINE

DEFINE CLASS XPostgreSql AS RemotePostgreSql
	FUNCTION Call(tcMethod, tv1, tv2, tv3, tv4)
		LOCAL lnN
		lnN = PCOUNT()
		DO CASE
		CASE lnN = 1
			RETURN EVALUATE("This." + tcMethod + "()")
		CASE lnN = 2
			RETURN EVALUATE("This." + tcMethod + "(tv1)")
		CASE lnN = 3
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2)")
		CASE lnN = 4
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3)")
		ENDCASE
		RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3, tv4)")
	ENDFUNC
ENDDEFINE

DEFINE CLASS XFirebird AS RemoteFirebird
	FUNCTION Call(tcMethod, tv1, tv2, tv3, tv4)
		LOCAL lnN
		lnN = PCOUNT()
		DO CASE
		CASE lnN = 1
			RETURN EVALUATE("This." + tcMethod + "()")
		CASE lnN = 2
			RETURN EVALUATE("This." + tcMethod + "(tv1)")
		CASE lnN = 3
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2)")
		CASE lnN = 4
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3)")
		ENDCASE
		RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3, tv4)")
	ENDFUNC
ENDDEFINE

DEFINE CLASS XSqlite AS RemoteSqlite
	FUNCTION Call(tcMethod, tv1, tv2, tv3, tv4)
		LOCAL lnN
		lnN = PCOUNT()
		DO CASE
		CASE lnN = 1
			RETURN EVALUATE("This." + tcMethod + "()")
		CASE lnN = 2
			RETURN EVALUATE("This." + tcMethod + "(tv1)")
		CASE lnN = 3
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2)")
		CASE lnN = 4
			RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3)")
		ENDCASE
		RETURN EVALUATE("This." + tcMethod + "(tv1, tv2, tv3, tv4)")
	ENDFUNC
ENDDEFINE
